version: 2.1
jobs:
  Unit tests:
    docker:
      - image: cypress/base:8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Setup Dependencies
          command: yarn install
      - run:
          name: Add css files to project
          command: yarn build-css
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Unit Tests
          command: yarn test

orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - Unit tests
      - cypress/run:
          executor: cypress/base-8
          cache-key: 'yarn-packages-{{ arch }}-{{ checksum "yarn.lock" }}'
          record: true
          yarn: true
          wait-on: "http://localhost:3002/"
          start: "yarn start"
