version: 2.1
orbs:
  cypress: cypress-io/cypress@1
jobs:
  build:
    docker:
      - image: cypress/base:8
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Setup Dependencies
          command: yarn install
      - run:
          name: Add css files to project
          command: yarn build-css
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Test
          command: yarn test
      - cypress/run:
          start: npm start
          wait-on: 'http://localhost:3002/'
      - run:
          name: e2e tests
          command: yarn cy:run

