version: 2
jobs:
  build:
    docker:
      - image: cypress/base:8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Setup Dependencies
          command: yarn install
      - run:
          name: Add css files to project
          command: yarn build-css
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Unit Tests
          command: yarn test
      - run:
          name: Run cypress tests
          command: yarn wait-on http://localhost:3002 && yarn cy:run




