# version: 2
# jobs:
#   build:
#     docker:
#       - image: cypress/base:8
#     steps:
#       - checkout
#       - restore_cache:
#           key: dependency-cache-{{ checksum "package.json" }}
#       - run:
#           name: Setup Dependencies
#           command: yarn install
#       - run:
#           name: Add css files to project
#           command: yarn build-css
#       - save_cache:
#           key: dependency-cache-{{ checksum "package.json" }}
#           paths:
#             - ./node_modules
#       - run:
#           name: Test
#           command: yarn test
#       - run:
#           name: e2e tests
#           command: yarn cy:run


version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Setup Dependencies
          command: yarn install
      - run:
          name: Add css files to project
          command: yarn build-css
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  Unit tests:
    docker:
      - image: circleci/node:8
    steps:
      - run: yarn test
  e2e tests:
    docker:
      - image: circleci/node:8
    steps:
      - run: yarn cy:run

workflows:
  version: 2
  as:
    jobs:
      - build
      - Unit tests

  arr:
    jobs:
      - e2e tests

  #   command: yarn install
  # run:
  #   name: Add css files to project
  #   command: yarn build-css
  # save_cache:
  #   key: dependency-cache-{{ checksum "package.json" }}
  #   paths: ./node_modules
  # run:
  #   name:
  #   command:
  # run:
  #   name:
  #   command:
